### PR TITLE
Issue#14

### LINKED ISSUE #14: Add the Sass Architecture and the User Profile Page
# Feature Request

- I will add the Sass, 4 folder architecture.
- I will also add a Global Media Query Manager, with flexible rem for all the screen widths
- I will also add the User Profile Page.

### PR DESCRIPTION
**Pull request by Elemento24**
# Pull Request 

## Live Link
https://seroton-inn.netlify.app/profile

## Proposed Changes
- Give a summary of the changes made in the repository. 
- List the dependencies used. 
- Also mention the issue number [Fixes #14 ].

## Types of changes made
- [ ] Fixed Bug
- [x] Added new Features
- [ ] Edited Documentations
- [ ] Enhanced the working of code
- [ ] Additional Changes

## Screenshots or GIFs (*if any*)
Screenshot from 2020-10-28 13-24-30
Screenshot from 2020-10-28 13-24-42
Screenshot from 2020-10-28 13-24-53
Screenshot from 2020-10-28 13-25-04
Screenshot from 2020-10-28 13-25-13
Screenshot from 2020-10-28 13-25-18

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [x] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [x] I have made the required changes to the documentations

### CODE REVIEW

**Comment by Elemento24** [comment]
Hey @Tlazypanda, can you please review this PR, and tell me if any further changes are required!

**Review by Tlazypanda — COMMENTED** [review]
Hey @Elemento24 some minor mobile view fixes reqd also not sure how text posts will be rendered 😅 take this up in a follow up pr merging this for now :)

**Comment by Elemento24** [comment]
Hey @Tlazypanda , Mam as per the Figma design, only pic based posts were there, so I assume that on the user profile page, there will be pics and title only. And then user can click on a post, to lead him or her to the show page! And in case, the requirements in the future change, I will update the design Mam!

**Comment by Tlazypanda** [comment]
Hmmm I understand that @Elemento24 but for just textual posts are we then showing a dummy image maybe of the mood room that it belongs too or something cc @uglyprincess @IC1101Virgo @stygian-96 ✌️

**Comment by uglyprincess** [comment]
> Hmmm I understand that @Elemento24 but for just textual posts are we then showing a dummy image maybe of the mood room that it belongs too or something cc @uglyprincess @IC1101Virgo @stygian-96 ✌️

We'll have a discussion in the group and make an issue accordingly! @Tlazypanda

**Pull request merged**
