### PR TITLE
Added tech stack for the project

### LINKED ISSUE #2: Add the project tech stack to the readme
# Feature Request

### Describe your problem
Add the project tech stack to the readme.

### PR DESCRIPTION
**Pull request by Jyotika999**
# Pull Request 

## Proposed Changes
- Added the tech stack of the project for front end and back end development
- Also mention the issue number [Fixes #2 ].

## Types of changes made
- [ ] Fixed Bug
- [x] Added new Features
- [x] Edited Documentations
- [x] Enhanced the working of code
- [x] Additional Changes

## Screenshot after the changes
Screenshot from 2020-10-11 15-31-24

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [x] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [x] I have made the required changes to the documentations

### CODE REVIEW

**Review by deepakDOTexe — APPROVED** [review]

**Review by Tlazypanda — COMMENTED** [review]
Hey @Jyotika999 I think @uglyprincess had mentioned react in the last meeting @uglyprincess can you please chime in and share the final thoughts on this? Thank you both :100:

**Comment by uglyprincess** [comment]
> Hey @Jyotika999 I think @uglyprincess had mentioned react in the last meeting @uglyprincess can you please chime in and share the final thoughts on this? Thank you both 💯


hey @Jyotika999 please update Swiper.js to React.js, and also we settled upon Firebase instead of passport.js

**Comment by Jyotika999** [comment]
Added the pull request with Required changes @Tlazypanda please review.

**Comment by Jyotika999** [comment]
Should i close this pull request?
 because I have added another new PR for the changes required.

**Pull request closed without merging**
