### PR TITLE
Added Project Idea to README.md (#1)

### LINKED ISSUE #1: Add the project idea in the readme
# Feature Request

### Describe your problem
Add the project idea and description to the readme.

### PR DESCRIPTION
**Pull request by uglyprincess**
# Pull Request 

## Proposed Changes
- Added Project Idea to the Readme
- Fixes #1 .

## Types of changes made
- [ ] Fixed Bug
- [ ] Added new Features
- [x] Edited Documentations
- [ ] Enhanced the working of code
- [ ] Additional Changes

## Additional Info
-

## Viability of Code
-

#### Mention(*if any*) specific Test Configurations used:
-

## Screenshots or GIFs (*if any*)
image
image

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [x] I have made the required changes to the documentations

### CODE REVIEW

**Comment by uglyprincess** [comment]
@Tlazypanda please review 🙌🏻

**Comment by deepakDOTexe** [comment]
@uglyprincess I think we don't need info about elevate-lab here

**Comment by uglyprincess** [comment]
> @uglyprincess I think we don't need info about elevate-lab here

changes made sir 👍🏻

**Review by Tlazypanda — APPROVED** [review]
Hey @uglyprincess approved :fire:

**Pull request merged**
